name: Tag Push Trigger

on:
  push:
    tags:
      - '*'

jobs:
  update-and-publish-connector:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Install commercetools CLI
        run: npm install -g @commercetools/cli
        
      - name: Login to commercetools CLI
        run: |
          commercetools auth login \
            --client-credentials \
            --client-id ${{ vars.CTP_CLIENT_ID }} \
            --client-secret ${{ secrets.CTP_CLIENT_SECRET }} \
            --region ${{ vars.CTP_REGION }} \
            --project-key ${{ vars.CTP_PROJECT_KEY }}
            
      - name: Update connector with current tag
        run: |
          commercetools connect connectorstaged update \
            --id ${{ vars.CONNECTOR_ID }} \
            --repository-tag ${{ github.ref_name }}
            
      - name: Publish connector
        run: |
          commercetools connect connectorstaged publish \
            --id ${{ vars.CONNECTOR_ID }}
